### ISSUE TITLE
Boolean default issue with new API

### ISSUE THREAD

**Issue by jamesmills** [kz/lifx-php#12]
https://github.com/kz/lifx-php/blob/bcc3ec61d7f8b835ed145accfa547a76f5d4fbb3/src/Lifx.php#L145

I have noticed that with the upgrade to the new API that if I pass true/false as true boolean values the Lifx API is returning an error.

```
Lifx::breatheLights(
        $selector = 'all',
        $color = 'purple',
        $from_color = null,
        $period = 1.0,
        $cycles = 1.0,
        $persist = false,
        $power_on = true,
        $peak = 0.5
    )
```

> "error": "persist does not have a valid value, power_on does not have a valid value"

However, if I change to send it like below, it works.

```
Lifx::breatheLights(
        $selector = 'all',
        $color = 'purple',
        $from_color = null,
        $period = 1.0,
        $cycles = 1.0,
        $persist = 'false',
        $power_on = 'true',
        $peak = 0.5
    )
```

**Comment by kz** [comment]
Hi James, thanks for raising this issue. It could be that PHP is converting booleans to `0`/`1`. I'm busy with university deadlines right now but will create a pull request for this during the weekend. Please also feel free to create a pull request!

**Comment by jamesmills** [comment]
Done @kz 

Thanks for creating the package.

**Comment by kz** [comment]
Thanks for the PR!
