### ISSUE TITLE
[Solved] Class 'Kz\Lifx' not found

### ISSUE THREAD

**Issue by zembrowski** [kz/lifx-php#5]
Hi there,

on a fresh Composer install I'm getting a "Class 'Kz\Lifx' not found" error. Using PHP 5.5.30.

The test file includes just vendor/autoload.php and then your example from the README.

Checked Guzzle PHP with a simple example. Works without a glitch.

Where can I start in order to find the bug?

Best regards,
Krzysztof

**Comment by zembrowski** [comment]
Dear Kelvin,

please change either the namespace in src/Lifx.php or the example to Kz\Lifx\Lifx($api_token), as this is the reason, why I had the above mentioned issue.

Thanks in advance.

Best regards,
Krzysztof

**Comment by kz** [comment]
Hi Krzysztof,

Unfortunately, I'm very busy with studies at the moment. Please can you spare some time to make a pull request to fix this?

Thanks,
Kelvin

**Comment by kz** [comment]
Thanks for the commit!
